[package]
name = "tagextract"
version = "0.1.0"
authors = ["Zachary Rivait <zchryrvt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
metaflac = "0.2.4"
